#! /bin/bash
. /usr/lib/network/network

tunnel_up() {
    load_profile "$1"

    if [[ -e "/sys/class/net/$INTERFACE" ]]; then
        report_fail "Interface $INTERFACE already exists."
        exit 1
    else
        ip tunnel add "$INTERFACE" mode "$MODE" remote "$REMOTE"
    fi

    if [[ -n "$LOCAL" ]]; then
        ip tunnel change "$INTERFACE" local "$LOCAL"
    fi

    "$CONN_DIR/ethernet" up "$1"
    return 0
}

tunnel_down() {
    load_profile "$1"

    "$CONN_DIR/ethernet" down "$1"
    ip tunnel del "$INTERFACE"

    return 0
}

tunnel_$1 "$2"
exit $?

# vim: set ts=4 et sw=4:
