#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /usr/lib/network/globals
. /etc/conf.d/netcfg

if [[ ! -x /usr/sbin/wpa_actiond ]]; then
    exit_stderr "Please install 'wpa_actiond' to use net-auto-wireless"
fi

if [[ -z "${WIRELESS_INTERFACE}" ]]; then
    exit_stderr "No interface name set. Add to /etc/conf.d/netcfg a line"$'\n' \
                " WIRELESS_INTERFACE='your_interface'"
fi

case "$1" in
    start)
        if ! ck_daemon net-auto-wireless; then
            exit_stderr "net-auto-wireless has already been started: try \"/etc/rc.d/net-auto-wireless restart\""
        fi
        # Ensure any device renaming has occurred as intended
        for daemon in "${DAEMONS[@]}"; do
            if [[ "$daemon" = "net-rename" ]]; then
                if ck_daemon net-rename; then
                    /etc/rc.d/net-rename start
                fi
            fi
        done

        stat_busy "Starting netcfg auto-wireless mode for interface ${WIRELESS_INTERFACE}"
        if /usr/bin/netcfg-wpa_actiond "${WIRELESS_INTERFACE}" >/dev/null; then
            add_daemon net-auto-wireless
            stat_done
        else
            stat_fail
        fi
        ;;
    stop)
        if ! ck_daemon net-auto-wireless; then
            stat_busy "Stopping netcfg auto-wireless mode for interface ${WIRELESS_INTERFACE}"
            if /usr/bin/netcfg-wpa_actiond stop "${WIRELESS_INTERFACE}" >/dev/null; then
                rm_daemon net-auto-wireless
                stat_done
            else
                stat_fail
            fi
        fi
        ;;
    restart)
        "$0" stop
        sleep 1
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
# vim: ft=sh ts=4 et sw=4:
