#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /usr/lib/network/globals

case "$1" in
  start)
    report_try "Renaming network devices"
    ifrename -p -t
    report_success

    add_daemon net-rename
    ;;
  stop)
    rm_daemon net-rename
    # No stop neccesary, but add one to look nice on shutdown.
    /bin/true
    ;;
  restart)
    "$0" start
    ;;
  *)
    exit_stderr "Usage: $0 {start|stop|restart}"
    ;;
esac

# vim: ft=sh ts=4 et sw=4:
