#! /bin/bash
. /usr/lib/network/network


ppp_up() {
    load_profile "$1"
    [[ -z "$PEER" ]] && PEER="provider"
    [[ -z "$PPP_TIMEOUT" ]] && PPP_TIMEOUT=30

    /usr/sbin/pppd call "$PEER" updetach child-timeout "$PPP_TIMEOUT" linkname "$PEER"

    if [[ $? -ne 0 ]]; then
       report_fail "Couldn't make pppd connection."
       return 1
    fi
}

ppp_down() {
    load_profile "$1"
    PIDFILE="/var/run/ppp-$(basename $PEER).pid"

    if [[ -e $PIDFILE ]]; then
        PID=$(head -1 $PIDFILE)
        [[ -n "$PID" ]] && kill "$PID"
    fi
}

ppp_$1 "$2"
exit $?

# vim: ft=sh ts=4 et sw=4:
