#! /bin/bash
. /usr/lib/network/network


ppp_up() {
    load_profile $1
    [[ -z "$PEER" ]] && PEER="provider"
    [[ -z "$PPP_TIMEOUT" ]] && PPP_TIMEOUT=30

    /usr/sbin/pppd call $PEER updetach child-timeout $PPP_TIMEOUT linkname $PEER

    if [[ $? -ne 0 ]]; then
       err_append "pppd connection failed"
       exit 1
    fi
}

ppp_down() {
    load_profile $1
    kill $(head -1 /var/run/ppp-$(basename $PEER).pid)
}

ppp_$1 $2
exit $?
# vim: set ts=4 et sw=4:
