#! /bin/bash
. /usr/lib/network/network

vlan_up() {
    load_profile "$1"

    if [[ -e "/sys/class/net/$INTERFACE" ]]; then
        report_fail "Interface $INTERFACE already exists."
        exit 1
    else
        bring_interface up "$VLAN_PHYS_DEV"
        ip link add link "$VLAN_PHYS_DEV" name "$INTERFACE" type vlan id "$VLAN_ID"
    fi
    "$CONN_DIR/ethernet" up "$1"
    return 0
}

vlan_down() {
    load_profile "$1"

    "$CONN_DIR/ethernet" down "$1"
    ip link delete "$INTERFACE"
    return 0
}

vlan_$1 "$2"
exit $?
# vim: set ts=4 et sw=4:
