#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
    start)
        # Ensure any device renaming has occurred as intended
        for daemon in "${DAEMONS[@]}"; do
            if [ "$daemon" = "${daemon#!}" -a "$daemon" = "net-rename" ]; then
                if ck_daemon net-rename; then
                    /etc/rc.d/net-rename start
                fi
          fi
        done

        # TODO: check if any way of using 'stacks' in bash
        for iface in ${AUTO_NETWORKS[@]}; do
            if [[ "${iface:0:4}" = "auto" ]]; then
                auto=$iface
            elif [[ "$auto" ]]; then
                /usr/bin/netcfg-$auto $iface
                [[ $? -eq 0 ]] && echo $iface >> /var/run/daemons/net-auto
                unset auto
            fi
        done       
        ;;
    stop)
        for iface in $(cat /var/run/daemons/net-auto); do
            netcfg interface-down $iface
        done
        rm_daemon net-auto
        ;;
    restart)
        $0 stop; sleep 1; $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"  
esac

# vim: set ts=4 et sw=4:
