#!/bin/bash
#
# ifplugd.action script for netctl

. /usr/lib/network/globals

PROFILE_FILE="$STATE_DIR/ifplugd_$1.profile"

case "$2" in
  up)
    echo "up"
    priority=0
    while read -r profile; do
        echo "Reading profile '$profile'"
        new_priority=$(
          source "$PROFILE_DIR/$profile"
          [[ "$Interface" == "$1" && "$Connection" == "ethernet" ]] || exit 1
          is_yes "${ExcludeAuto:-no}" && exit 1
          : ${Priority:=0}

          echo "$Priority"
          exit 0
        )
        if (( $? == 0 )); then
            if [[ -z $selected ]] || (( new_priority >= priority )); then
                selected=$profile
                priority=$new_priority
            fi
        fi
    done < <(list_profiles)
    if [[ $selected ]]; then
        if ForceConnect=yes "$SUBR_DIR/network" start "$selected"; then
            mkdir -p "$(dirname "$PROFILE_FILE")"
            printf "%s" "$selected" > "$PROFILE_FILE"
            exit 0
        fi
    fi
  ;;
  down)
    if [[ -e "$PROFILE_FILE" ]]; then
        profile=$(< "$PROFILE_FILE")
        "$SUBR_DIR/network" stop "$profile"
        rm -f "$PROFILE_FILE"
        exit 0
    fi
  ;;
  *)
    echo "Wrong arguments" >&2
  ;;
esac

exit 1


# vim: ft=sh ts=4 et sw=4:
