#!/bin/bash

. /usr/lib/network/globals

case "$1" in
    start)
        if ! ck_daemon net-profiles; then
            exit_stderr "net-profiles has already been started.  Try '/etc/rc.d/net-profiles restart'"
        fi

        # Ensure any device renaming has occurred as intended
        for daemon in "${DAEMONS[@]}"; do
            if [ "$daemon" = "${daemon#!}" -a "$daemon" = "net-rename" ]; then
                if ck_daemon net-rename; then
                    /etc/rc.d/net-rename start
                fi
          fi
        done

        # $NET env var is passed from the kernel boot line
        [ ! "$NETWORKS_MENU_TIMEOUT" ] && NETWORKS_MENU_TIMEOUT=5 
        
        if [[ "$NET" = "menu" ]]; then
                /usr/bin/netcfg-menu $NETWORKS_MENU_TIMEOUT
        elif [[ "$NET" ]]; then
                /usr/bin/netcfg2 -c $NET
        else 
            # No NET= passed at boot, go to NETWORKS=()
            for network in ${NETWORKS[@]}; do
                case $network in
                    menu) # Pull up menu of networks
                        /usr/bin/netcfg-menu $NETWORKS_MENU_TIMEOUT
                        ;;
                    *) # Either interface or profile
                        if [ "$network" = "${network#!}" ]; then # otherwise profile
                            /usr/bin/netcfg2 -c $network
                        fi
                        ;;
                esac
            done
        fi            

        add_daemon net-profiles
        ;;
    stop)
        # shutdown any profiles started by netcfg (or from NET_PROFILES in rc.conf)
        /usr/bin/netcfg2 -a
        rm_daemon net-profiles
        ;;
    restart)
        $0 stop; sleep 1; $0 start
        ;;
    *)
        exit_stderr "Usage: $0 {start|stop|restart}"
esac

# vim: set ts=4 et sw=4:
