#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /usr/lib/network/network

NETCFG_VER=2.2.0_B1

version()
{
    echo "netcfg v$NETCFG_VER"
}

usage()
{
    version
    echo "Usage:"
    echo "      Start specified profile:    netcfg profile " 
    echo "      Other functions:            netcfg argument profile"
    echo "Arguments:"
    echo "-a, all-down       Take all active profiles down"
    echo "-c, check-iface    Do not start profile if interface is already up"
    echo "-d, down           Take specified profile down"
    echo "-h, help           This help message"
    echo "-i, iface-down     Take down profile active on specified interface"
		echo "-r, reconnect      Disconnect and reconnect specified profile"
		echo "-u, up             Start specified profile"
    echo "-v, version        Output version information and exit"
    echo "    all-resume     Resume previously suspended profiles and reconnect them"
    echo "    all-suspend    Store a list of current running profiles and suspend them"
}

# TODO: Re-add ROOT check and rewrite with getopts from BashFAQ

case $1 in
    --version|-v|version) 
        version;;
    --help|-h|help) 
        usage;;
    -c|check-iface|-u|up)
        CHECK="YES"; 
        profile_up $2;;
   clean)
        rm /var/run/network/interfaces/* 2> /dev/null
        rm /var/run/network/profiles/* 2> /dev/null
				rm /var/run/network/suspend/* 2> /dev/null
				rm /var/run/network/last_profile 2> /dev/null
        killall wpa_supplicant 2> /dev/null
        killall dhcpcd 2> /dev/null
        ;;	
    -d|down) 
        profile_down $2;;
    -i|iface-down) 
        interface_down $2;;
    -a|all-down) 
        all_down;; 
		-r|reconnect)
				profile_down $2
				profile_up $2;;
    all-resume)
        all_resume;;
    all-suspend)
        all_suspend;;
    -*|--*) 
        usage;;
    *)  
        if [ -n "$1" ]; then
            profile_up $1
        else
            usage
        fi
        ;;  
esac
exit $?
# vim: set ts=2 noet:
