#! /bin/bash
ppp_up() {
    [[ -z "$PEER" ]] && PEER="provider"
    [[ -z "$PPP_TIMEOUT" ]] && PPP_TIMEOUT=30

    /usr/sbin/pppd call $PEER updetach child-timeout $PPP_TIMEOUT linkname $PEER

    if [[ $? -ne 0 ]]; then
       err_append "pppd connection failed"
       exit 1
    fi
}

ppp_down() {
    kill $(head -1 /var/run/ppp-$(basename $PEER).pid)
}

ppp_clean_scope() {
    unset PPP_PEER PPP_TIMEOUT
}
# vim: set ts=4 et sw=4:
